// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExperimentalFeature = { 
/**
 * Stable key used in config.toml and CLI flag toggles.
 */
flagName: string, 
/**
 * User-facing display name shown in the experimental features UI.
 */
displayName: string, 
/**
 * Short summary describing what the feature does.
 */
description: string, 
/**
 * Announcement copy shown to users when the feature is introduced.
 */
announcement: string, 
/**
 * Whether this feature is currently enabled in the loaded config.
 */
enabled: boolean, 
/**
 * Whether this feature is enabled by default.
 */
defaultEnabled: boolean, };
