// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Personality } from "../Personality";
import type { JsonValue } from "../serde_json/JsonValue";
import type { AskForApproval } from "./AskForApproval";
import type { SandboxMode } from "./SandboxMode";

export type ThreadStartParams = {model?: string | null, modelProvider?: string | null, cwd?: string | null, approvalPolicy?: AskForApproval | null, sandbox?: SandboxMode | null, config?: { [key in string]?: JsonValue } | null, baseInstructions?: string | null, developerInstructions?: string | null, personality?: Personality | null, serviceTier?: string | null, ephemeral?: boolean | null, /**
 * If true, opt into emitting raw response items on the event stream.
 *
 * This is for internal use only (e.g. Codex Cloud).
 * (TODO): Figure out a better way to categorize internal / experimental events & protocols.
 */
experimentalRawEvents: boolean};
