// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressTraceCategory } from "./ProgressTraceCategory";
import type { ProgressTraceState } from "./ProgressTraceState";

export type TurnProgressTraceNotification = { threadId: string, turnId: string, category: ProgressTraceCategory, state: ProgressTraceState, label: string | null, };
