// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { CodexErrorInfo } from "./CodexErrorInfo";

export type ErrorEvent = { message: string, codex_error_info: CodexErrorInfo | null, client_user_message_id: string | null, };
