// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Structured review result produced by a post-turn completion reviewer.
 */
export type PostTurnCompletionReviewOutputEvent = { evaluation: string, fix_actions_advised: boolean, };
