// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ProgressTraceCategory } from "./ProgressTraceCategory";
import type { ProgressTraceState } from "./ProgressTraceState";
import type { ThreadId } from "./ThreadId";

export type ProgressTraceEvent = { thread_id: ThreadId, turn_id: string, category: ProgressTraceCategory, state: ProgressTraceState, label?: string, source?: string, };
