// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Controls the service tier requested from the Responses API.
 */
export type ServiceTier = "fast" | "flex";
