// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnPauseReason } from "./TurnPauseReason";

export type TurnPausedEvent = { turn_id: string, reason: TurnPauseReason, };
