// GENERATED CODE! DO NOT MODIFY BY HAND!

// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { TurnContinuationSource } from "./TurnContinuationSource";

export type TurnContinuedEvent = { continued_from_turn_id: string | null, source: TurnContinuationSource, };
